// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 16 Nov 2021 17:36:23 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package liquiddsp provides Go bindings for liquid-dsp
*/
package liquiddsp
