// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 18 Nov 2021 16:40:08 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package liquiddsp

/*
#cgo CFLAGS: -msse4.1 -Wall -fPIC -I. -I.. -I../include
#cgo LDFLAGS: -lm ${SRCDIR}/../libliquid.a
#include <inttypes.h>
#include <complex.h>
#include "liquid.h"
#include "liquid.internal.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// QpacketmodemCreate function as declared in include/liquid.h:4876
func QpacketmodemCreate() Qpacketmodem {
	__ret := C.qpacketmodem_create()
	__v := *(*Qpacketmodem)(unsafe.Pointer(&__ret))
	return __v
}

// QpacketmodemDestroy function as declared in include/liquid.h:4877
func QpacketmodemDestroy(Q Qpacketmodem) int32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	__ret := C.qpacketmodem_destroy(cQ)
	__v := (int32)(__ret)
	return __v
}

// QpacketmodemReset function as declared in include/liquid.h:4878
func QpacketmodemReset(Q Qpacketmodem) int32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	__ret := C.qpacketmodem_reset(cQ)
	__v := (int32)(__ret)
	return __v
}

// QpacketmodemPrint function as declared in include/liquid.h:4879
func QpacketmodemPrint(Q Qpacketmodem) int32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	__ret := C.qpacketmodem_print(cQ)
	__v := (int32)(__ret)
	return __v
}

// QpacketmodemConfigure function as declared in include/liquid.h:4881
func QpacketmodemConfigure(Q Qpacketmodem, PayloadLen uint32, Check CrcScheme, Fec0 FecScheme, Fec1 FecScheme, Ms int32) int32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	cPayloadLen, _ := (C.uint)(PayloadLen), cgoAllocsUnknown
	cCheck, _ := (C.crc_scheme)(Check), cgoAllocsUnknown
	cFec0, _ := (C.fec_scheme)(Fec0), cgoAllocsUnknown
	cFec1, _ := (C.fec_scheme)(Fec1), cgoAllocsUnknown
	cMs, _ := (C.int)(Ms), cgoAllocsUnknown
	__ret := C.qpacketmodem_configure(cQ, cPayloadLen, cCheck, cFec0, cFec1, cMs)
	__v := (int32)(__ret)
	return __v
}

// QpacketmodemGetFrameLen function as declared in include/liquid.h:4889
func QpacketmodemGetFrameLen(Q Qpacketmodem) uint32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	__ret := C.qpacketmodem_get_frame_len(cQ)
	__v := (uint32)(__ret)
	return __v
}

// QpacketmodemGetPayloadLen function as declared in include/liquid.h:4892
func QpacketmodemGetPayloadLen(Q Qpacketmodem) uint32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	__ret := C.qpacketmodem_get_payload_len(cQ)
	__v := (uint32)(__ret)
	return __v
}

// QpacketmodemGetCrc function as declared in include/liquid.h:4895
func QpacketmodemGetCrc(Q Qpacketmodem) uint32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	__ret := C.qpacketmodem_get_crc(cQ)
	__v := (uint32)(__ret)
	return __v
}

// QpacketmodemGetFec0 function as declared in include/liquid.h:4896
func QpacketmodemGetFec0(Q Qpacketmodem) uint32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	__ret := C.qpacketmodem_get_fec0(cQ)
	__v := (uint32)(__ret)
	return __v
}

// QpacketmodemGetFec1 function as declared in include/liquid.h:4897
func QpacketmodemGetFec1(Q Qpacketmodem) uint32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	__ret := C.qpacketmodem_get_fec1(cQ)
	__v := (uint32)(__ret)
	return __v
}

// QpacketmodemGetModscheme function as declared in include/liquid.h:4898
func QpacketmodemGetModscheme(Q Qpacketmodem) uint32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	__ret := C.qpacketmodem_get_modscheme(cQ)
	__v := (uint32)(__ret)
	return __v
}

// QpacketmodemGetDemodulatorPhaseError function as declared in include/liquid.h:4900
func QpacketmodemGetDemodulatorPhaseError(Q Qpacketmodem) float32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	__ret := C.qpacketmodem_get_demodulator_phase_error(cQ)
	__v := (float32)(__ret)
	return __v
}

// QpacketmodemGetDemodulatorEvm function as declared in include/liquid.h:4901
func QpacketmodemGetDemodulatorEvm(Q Qpacketmodem) float32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	__ret := C.qpacketmodem_get_demodulator_evm(cQ)
	__v := (float32)(__ret)
	return __v
}

// QpacketmodemEncodeSyms function as declared in include/liquid.h:4907
func QpacketmodemEncodeSyms(Q Qpacketmodem, Payload string, Syms []byte) int32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	cPayload, _ := unpackPUcharString(Payload)
	cSyms, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Syms)).Data)), cgoAllocsUnknown
	__ret := C.qpacketmodem_encode_syms(cQ, cPayload, cSyms)
	__v := (int32)(__ret)
	return __v
}

// QpacketmodemDecodeSyms function as declared in include/liquid.h:4915
func QpacketmodemDecodeSyms(Q Qpacketmodem, Syms []byte, Payload []byte) int32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	cSyms, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Syms)).Data)), cgoAllocsUnknown
	cPayload, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Payload)).Data)), cgoAllocsUnknown
	__ret := C.qpacketmodem_decode_syms(cQ, cSyms, cPayload)
	__v := (int32)(__ret)
	return __v
}

// QpacketmodemDecodeBits function as declared in include/liquid.h:4923
func QpacketmodemDecodeBits(Q Qpacketmodem, Bits []byte, Payload []byte) int32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	cBits, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Bits)).Data)), cgoAllocsUnknown
	cPayload, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Payload)).Data)), cgoAllocsUnknown
	__ret := C.qpacketmodem_decode_bits(cQ, cBits, cPayload)
	__v := (int32)(__ret)
	return __v
}

// QpacketmodemEncode function as declared in include/liquid.h:4931
func QpacketmodemEncode(Q Qpacketmodem, Payload string, Frame []complex64) int32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	cPayload, _ := unpackPUcharString(Payload)
	cFrame, _ := unpackArgSComplex64(Frame)
	__ret := C.qpacketmodem_encode(cQ, cPayload, cFrame)
	packSComplex64(Frame, cFrame)
	__v := (int32)(__ret)
	return __v
}

// QpacketmodemDecode function as declared in include/liquid.h:4940
func QpacketmodemDecode(Q Qpacketmodem, Frame []complex64, Payload []byte) int32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	cFrame, _ := unpackArgSComplex64(Frame)
	cPayload, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Payload)).Data)), cgoAllocsUnknown
	__ret := C.qpacketmodem_decode(cQ, cFrame, cPayload)
	packSComplex64(Frame, cFrame)
	__v := (int32)(__ret)
	return __v
}

// QpacketmodemDecodeSoft function as declared in include/liquid.h:4949
func QpacketmodemDecodeSoft(Q Qpacketmodem, Frame []complex64, Payload []byte) int32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	cFrame, _ := unpackArgSComplex64(Frame)
	cPayload, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Payload)).Data)), cgoAllocsUnknown
	__ret := C.qpacketmodem_decode_soft(cQ, cFrame, cPayload)
	packSComplex64(Frame, cFrame)
	__v := (int32)(__ret)
	return __v
}

// QpacketmodemDecodeSoftSym function as declared in include/liquid.h:4953
func QpacketmodemDecodeSoftSym(Q Qpacketmodem, Symbol complex64) int32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	cSymbol := C.complexfloat(Symbol)
	__ret := C.qpacketmodem_decode_soft_sym(cQ, cSymbol)
	__v := (int32)(__ret)
	return __v
}

// QpacketmodemDecodeSoftPayload function as declared in include/liquid.h:4956
func QpacketmodemDecodeSoftPayload(Q Qpacketmodem, Payload []byte) int32 {
	cQ, _ := *(*C.qpacketmodem)(unsafe.Pointer(&Q)), cgoAllocsUnknown
	cPayload, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Payload)).Data)), cgoAllocsUnknown
	__ret := C.qpacketmodem_decode_soft_payload(cQ, cPayload)
	__v := (int32)(__ret)
	return __v
}

// CountBitErrorsArray function as declared in include/liquid.h:7347
func CountBitErrorsArray(Msg0 []byte, Msg1 []byte, N uint32) uint32 {
	cMsg0, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Msg0)).Data)), cgoAllocsUnknown
	cMsg1, _ := (*C.uchar)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Msg1)).Data)), cgoAllocsUnknown
	cN, _ := (C.uint)(N), cgoAllocsUnknown
	__ret := C.count_bit_errors_array(cMsg0, cMsg1, cN)
	__v := (uint32)(__ret)
	return __v
}

// Randnf function as declared in include/liquid.h:8774
func Randnf() float32 {
	__ret := C.randnf()
	__v := (float32)(__ret)
	return __v
}
