// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 24 Nov 2021 17:31:22 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package liquiddsp

/*
#cgo CFLAGS: -msse4.1 -Wall -fPIC -I. -I.. -I../include
#cgo LDFLAGS: -lm ${SRCDIR}/../libliquid.a
#include <inttypes.h>
#include <complex.h>
#include "liquid.h"
#include "liquid.internal.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
)

// CountBitErrorsArray function as declared in include/liquid.h:7347
func CountBitErrorsArray(msg0 []byte, msg1 []byte, n uint32) uint32 {
	count := C.count_bit_errors_array((*C.uchar)(&(msg0[0])), (*C.uchar)(&(msg1[0])), C.uint(n))
	runtime.KeepAlive(msg1)
	runtime.KeepAlive(msg0)
	return uint32(count)
}

// Randnf function as declared in include/liquid.h:8774
func Randnf() float32 {
	__ret := C.randnf()
	__v := (float32)(__ret)
	return __v
}

// LiquidCountOnes function as declared in include/liquid.h:9107
func LiquidCountOnes(x uint32) uint32 {
	return uint32(C.liquid_count_ones(C.uint(x)))
}
