// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 24 Nov 2021 17:31:22 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package liquiddsp

/*
#cgo CFLAGS: -msse4.1 -Wall -fPIC -I. -I.. -I../include
#cgo LDFLAGS: -lm ${SRCDIR}/../libliquid.a
#include <inttypes.h>
#include <complex.h>
#include "liquid.h"
#include "liquid.internal.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// FrameSyncStats as declared in include/liquid.h:4822
type FrameSyncStats struct {
	Evm          float32
	Rssi         float32
	Cfo          float32
	Framesyms    []Complexfloat
	NumFramesyms uint32
	ModScheme    uint32
	ModBps       uint32
	Check        uint32
	Fec0         uint32
	Fec1         uint32
}

var FrameSyncStatsDefault FrameSyncStats

// FrameSyncStatsInitDefault function as declared in include/liquid.h:4828
func (stats *FrameSyncStats) InitDefault() error {
	err := C.framesyncstats_init_default((*C.framesyncstats_s)(unsafe.Pointer(stats)))
	runtime.KeepAlive(stats)
	return maybeError(err)
}

// FrameSyncStatsPrint function as declared in include/liquid.h:4831
func (stats *FrameSyncStats) Print() error {
	err := C.framesyncstats_print((*C.framesyncstats_s)(unsafe.Pointer(stats)))
	runtime.KeepAlive(stats)
	return maybeError(err)
}

// FrameDataStats as declared in include/liquid.h:4840
type FrameDataStats struct {
	NumFramesDetected uint32
	NumHeadersValid   uint32
	NumPayloadsValid  uint32
	NumBytesReceived  uint32
}

// FrameDataStatsReset function as declared in include/liquid.h:4843
func (stats *FrameDataStats) Reset() error {
	err := C.framedatastats_reset((*C.framedatastats_s)(unsafe.Pointer(stats)))
	runtime.KeepAlive(stats)
	return maybeError(err)
}

// FrameDataStatsPrint function as declared in include/liquid.h:4846
func (stats *FrameDataStats) Print() error {
	err := C.framedatastats_print((*C.framedatastats_s)(unsafe.Pointer(stats)))
	runtime.KeepAlive(stats)
	return maybeError(err)
}

// Qpacketmodem as declared in include/liquid.h:4873
type Qpacketmodem C.qpacketmodem

// FlexFrameGenProps as declared in include/liquid.h:5112
type FlexFrameGenProps struct {
	Check     uint32
	Fec0      uint32
	Fec1      uint32
	ModScheme uint32
}

// FlexFrameGenPropsInitDefault function as declared in include/liquid.h:5114
func (fgprops *FlexFrameGenProps) InitDefault() error {
	err := C.flexframegenprops_init_default((*C.flexframegenprops_s)(unsafe.Pointer(fgprops)))
	runtime.KeepAlive(fgprops)
	return maybeError(err)
}
