// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 16 Nov 2021 17:36:02 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package liquiddsp

/*
#cgo CFLAGS: -msse4.1 -Wall -fPIC -I. -I.. -I../include
#cgo LDFLAGS: -L${SRCDIR}/.. -lliquid
#include <inttypes.h>
#include <complex.h>
#include "liquid.h"
#include "liquid.internal.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// LiquidFloatComplex type as declared in include/liquid.h:148
type LiquidFloatComplex C.liquid_float_complex

// GMSKMod as declared in include/liquid.h:7485
type GMSKMod C.gmskmod

// GMSKDemod as declared in include/liquid.h:7503
type GMSKDemod C.gmskdem
